# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import generated_pb2 as generated__pb2


class ProtocolServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ParseUAST = channel.unary_unary(
        '/github.com.bblfsh.sdk.protocol.ProtocolService/ParseUAST',
        request_serializer=generated__pb2.ParseUASTRequest.SerializeToString,
        response_deserializer=generated__pb2.ParseUASTResponse.FromString,
        )


class ProtocolServiceServicer(object):

  def ParseUAST(self, request, context):
    """ParseUAST uses DefaultParser to process the given UAST parsing request.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProtocolServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ParseUAST': grpc.unary_unary_rpc_method_handler(
          servicer.ParseUAST,
          request_deserializer=generated__pb2.ParseUASTRequest.FromString,
          response_serializer=generated__pb2.ParseUASTResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'github.com.bblfsh.sdk.protocol.ProtocolService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
